config:
  aws:region: us-east-1
  codenames-twisted:domain: codenames.cnexans.com
  codenames-twisted:acmeEmail: admin@cnexans.com
encryptionsalt: v1:yNuXI0wjW2w=:v1:byHyfCmsXfs+ZixP:6eZd0LejW9VTRoPeS9p/PTgwBmYOFQ==
